name: "Build Docs"
description: "build jekyll docs"
inputs:
  version:
    description: "Version number"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: "Setup dependencies and asdf with cache"
      uses: ./.github/actions/setup-dependencies-asdf-with-cache
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Build with Jekyll
      working-directory: ./docs
      # Outputs to the './_site' directory by default
      shell: bash
      run: make build-ci BASE_URL="${BASE_URL}" VERSION="${VERSION}"
      env:
        JEKYLL_ENV: production
        BASE_URL: ${{ steps.pages.outputs.base_path }}
        VERSION: ${{ inputs.version }}
    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v3
      with:
        path: "docs/_site/"
        name: jekyll-docs-${{ inputs.version }}

    - name: tar schema
      run: tar -cvf artifact.tar src/cloudeventjekylldocs/output/schemas
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: "artifact.tar"
        name: schemas-${{ inputs.version }}
