name: "Build Docs"
description: "build jekyll docs"
inputs:
  version:
    description: "Version number"
    required: true
  node-version:
    description: 'Node.js version'
    required: true
  GITHUB_TOKEN:
    description: "Token for access to github package registry"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5
    - uses: ./.github/actions/node-install
      with:
        node-version: ${{ inputs.node-version }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    - name: Npm cli install
      working-directory: ./docs
      run: npm ci
      shell: bash
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.267.0
      with:
        ruby-version: "3.4.7" # Not needed with a .ruby-version file
        bundler-cache: true # Enable automatic gem caching
        cache-version: 0 # Increment this number if you need to re-download cached gems
        working-directory: "./docs"
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Build with Jekyll
      working-directory: ./docs
      # Outputs to the './_site' directory by default
      shell: bash
      run: make build-ci BASE_URL="${BASE_URL}" VERSION="${VERSION}"
      #run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production
        BASE_URL: ${{ steps.pages.outputs.base_path }}
        VERSION: ${{ inputs.version }}
    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v3
      with:
        path: "docs/_site/"
        name: jekyll-docs-${{ inputs.version }}

    - name: tar schema
      run: tar -cvf artifact.tar src/cloudeventjekylldocs/output/schemas
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: "artifact.tar"
        name: schemas-${{ inputs.version }}
