/**
 * Root Jest config — runs all TypeScript workspace test suites in
 * parallel via Jest's native `projects` support.
 *
 * ⚠️  THIS FILE IS AUTO-GENERATED. Do not edit it directly.
 *
 * Generated by scripts/generate-parallel-jest-config.ts
 */

/** @type {import('jest').Config} */
module.exports = {
  collectCoverage: true,
  coverageProvider: "babel",
  coverageDirectory: ".reports/unit/coverage",
  coverageReporters: [
    "text",
    "lcov",
    "html",
    "cobertura",
  ],
  coverageThreshold: {
    "/root/repos/nhs-notify-digital-letters/lambdas/file-scanner-lambda/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/key-generation/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/refresh-apim-access-token/": {
      "branches": 100,
      "functions": 100,
      "lines": 90,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/pdm-mock-lambda/": {
      "branches": 100,
      "functions": 100,
      "lines": 90,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/pdm-poll-lambda/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/ttl-create-lambda/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/ttl-handle-expiry-lambda/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/ttl-poll-lambda/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/pdm-uploader-lambda/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/print-sender-lambda/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/core-notifier-lambda/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/print-status-handler/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/print-analyser/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/report-scheduler/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/report-event-transformer/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/move-scanned-files-lambda/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/lambdas/report-generator/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/utils/utils/": {
      "branches": 85,
      "functions": 85,
      "lines": 85,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/utils/sender-management/": {
      "branches": 84,
      "functions": 91,
      "lines": 90,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/src/cloudevents/": {
      "branches": 60,
      "functions": 60,
      "lines": 60,
      "statements": 60,
    },
    "/root/repos/nhs-notify-digital-letters/src/python-schema-generator/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
    "/root/repos/nhs-notify-digital-letters/src/typescript-schema-generator/": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": -10,
    },
  },
  projects: [
    // lambdas/file-scanner-lambda
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/file-scanner-lambda",
      "displayName": "lambdas/file-scanner-lambda",
    },

    // lambdas/key-generation
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
        "lambda.ts",
        "/config.ts",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/key-generation",
      "displayName": "lambdas/key-generation",
    },

    // lambdas/refresh-apim-access-token
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
        "cli.ts",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/refresh-apim-access-token",
      "displayName": "lambdas/refresh-apim-access-token",
    },

    // lambdas/pdm-mock-lambda
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/pdm-mock-lambda",
      "displayName": "lambdas/pdm-mock-lambda",
    },

    // lambdas/pdm-poll-lambda
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/pdm-poll-lambda",
      "displayName": "lambdas/pdm-poll-lambda",
    },

    // lambdas/ttl-create-lambda
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/ttl-create-lambda",
      "displayName": "lambdas/ttl-create-lambda",
    },

    // lambdas/ttl-handle-expiry-lambda
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/ttl-handle-expiry-lambda",
      "displayName": "lambdas/ttl-handle-expiry-lambda",
    },

    // lambdas/ttl-poll-lambda
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/ttl-poll-lambda",
      "displayName": "lambdas/ttl-poll-lambda",
    },

    // lambdas/pdm-uploader-lambda
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/pdm-uploader-lambda",
      "displayName": "lambdas/pdm-uploader-lambda",
    },

    // lambdas/print-sender-lambda
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/print-sender-lambda",
      "displayName": "lambdas/print-sender-lambda",
    },

    // lambdas/core-notifier-lambda
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/core-notifier-lambda",
      "displayName": "lambdas/core-notifier-lambda",
    },

    // lambdas/print-status-handler
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "transformIgnorePatterns": [
        "node_modules/(?!@nhsdigital/nhs-notify-event-schemas-supplier-api)",
      ],
      "rootDir": "<rootDir>/lambdas/print-status-handler",
      "displayName": "lambdas/print-status-handler",
    },

    // lambdas/print-analyser
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/print-analyser",
      "displayName": "lambdas/print-analyser",
    },

    // lambdas/report-scheduler
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/report-scheduler",
      "displayName": "lambdas/report-scheduler",
    },

    // lambdas/report-event-transformer
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/report-event-transformer",
      "displayName": "lambdas/report-event-transformer",
    },

    // lambdas/move-scanned-files-lambda
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/move-scanned-files-lambda",
      "displayName": "lambdas/move-scanned-files-lambda",
    },

    // lambdas/report-generator
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/lambdas/report-generator",
      "displayName": "lambdas/report-generator",
    },

    // utils/utils
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
        "index.ts",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/utils/utils",
      "displayName": "utils/utils",
    },

    // utils/sender-management
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/utils/sender-management",
      "displayName": "utils/sender-management",
    },

    // src/cloudevents
    {
      "preset": "ts-jest",
      "testEnvironment": "node",
      "roots": [
        "<rootDir>",
      ],
      "testMatch": [
        "**/__tests__/**/*.ts",
        "**/?(*.)+(spec|test).ts",
      ],
      "transform": {
        "^.+\\.ts$": [
          "ts-jest",
          {
            "tsconfig": {
              "esModuleInterop": true,
              "allowSyntheticDefaultImports": true,
              "allowImportingTsExtensions": true,
              "module": "commonjs",
              "target": "ES2020",
              "moduleResolution": "node",
              "noEmit": true,
            },
            "diagnostics": {
              "ignoreCodes": [
                1343,
              ],
            },
          },
        ],
      },
      "collectCoverageFrom": [
        "tools/**/*.{ts,js,cjs}",
        "!tools/**/*.d.ts",
        "!tools/**/__tests__/**",
        "!tools/**/*.test.ts",
        "!tools/**/*.spec.ts",
        "!tools/builder/build-schema.ts",
        "!tools/generator/generate-example.ts",
        "!tools/generator/manual-bundle-schema.ts",
        "!tools/validator/validate.ts",
      ],
      "coveragePathIgnorePatterns": [
        "/node_modules/",
        "/__tests__/",
      ],
      "moduleFileExtensions": [
        "ts",
        "js",
        "json",
      ],
      "moduleNameMapper": {
        "^(.*)\\.ts$": "$1",
      },
      "testTimeout": 10000,
      "rootDir": "<rootDir>/src/cloudevents",
      "displayName": "src/cloudevents",
    },

    // src/python-schema-generator
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
        "src/merge-allof-cli.ts",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/src/python-schema-generator",
      "displayName": "src/python-schema-generator",
    },

    // src/typescript-schema-generator
    {
      "preset": "ts-jest",
      "clearMocks": true,
      "collectCoverageFrom": [
        "src/**/*.{ts,tsx}",
        "!src/**/*.d.ts",
        "!src/**/__tests__/**",
        "!src/**/*.test.{ts,tsx}",
        "!src/**/*.spec.{ts,tsx}",
      ],
      "coveragePathIgnorePatterns": [
        "/__tests__/",
        "src/generate-types-cli.ts",
        "src/generate-validators-cli.ts",
      ],
      "transform": {
        "^.+\\.ts$": "ts-jest",
      },
      "testPathIgnorePatterns": [
        ".build",
      ],
      "testMatch": [
        "**/?(*.)+(spec|test).[jt]s?(x)",
      ],
      "reporters": [
        "default",
        [
          "jest-html-reporter",
          {
            "pageTitle": "Test Report",
            "outputPath": "./.reports/unit/test-report.html",
            "includeFailureMsg": true,
          },
        ],
      ],
      "testEnvironment": "node",
      "moduleDirectories": [
        "node_modules",
        "src",
      ],
      "rootDir": "<rootDir>/src/typescript-schema-generator",
      "displayName": "src/typescript-schema-generator",
    }
  ],
};
