name: Acceptance tests
description: "Run acceptance tests for this repo"

inputs:
  testType:
    description: Type of test to run
    required: true
    default: main

  targetEnvironment:
    description: Name of the environment under test
    required: true
    default: main

  targetAccountGroup:
    description: Name of the account group under test
    default: nhs-notify-digital-letters-dev
    required: true

  targetComponent:
    description: Name of the component under test
    default: dl

runs:
  using: "composite"

  steps:
    - name: Get Node version
      id: nodejs_version
      shell: bash
      run: |
        echo "nodejs_version=$(grep "^nodejs\s" .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT
    - uses: ./.github/actions/node-install
      with:
        node-version: ${{ steps.nodejs_version.outputs.nodejs_version }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
    - name: "Install dependencies"
      shell: bash
      run: |
        npm ci
    - name: "Generate dependencies"
      shell: bash
      run: |
        npm run generate-dependencies
    - name: Run test - ${{ inputs.testType }}
      shell: bash
      run: |
        set -euo pipefail
        case "$TEST_TYPE" in
          main|integration|unit)
            make "test-$TEST_TYPE"
            ;;
          *)
            echo "Invalid testType: $TEST_TYPE" >&2
            exit 1
            ;;
        esac
      env:
        TEST_TYPE: ${{ inputs.testType }}
        ENVIRONMENT: ${{ inputs.targetEnvironment }}
    - name: Archive integration test results
      if: ${{ inputs.testType == 'integration' }}
      uses: actions/upload-artifact@v4
      with:
        name: Integration test report
        path: "tests/playwright/playwright-report"
