/**
 * Generates jest.config.cjs from the individual workspace jest.config.ts files.
 */

import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

const repoRoot = path.resolve(__dirname, '..');
const outputPath = path.join(repoRoot, 'jest.config.cjs');

interface PackageJson {
  workspaces?: string[];
}

const rootPkg = JSON.parse(
  fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf8'),
) as PackageJson;

const workspaces: string[] = rootPkg.workspaces ?? [];

/**
 * Inline TypeScript written to a temp .ts file and executed by tsx so each
 * workspace jest.config.ts is evaluated in an isolated Node process with a
 * fresh module registry (preventing shared mutable baseJestConfig state).
 */
const EVALUATOR = (configPath: string): string => `
import config from ${JSON.stringify(configPath)};
process.stdout.write(JSON.stringify(config));
`;

/** Serialise a plain JS value to source code, indented with the given prefix. */
function serialise(value: unknown, indent = '  '): string {
  if (value === null) return 'null';
  if (value === undefined) return 'undefined';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number' || typeof value === 'boolean')
    return String(value);

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value
      .map((v) => `${indent}  ${serialise(v, indent + '  ')}`)
      .join(',\n');
    return `[\n${items},\n${indent}]`;
  }

  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    );
    if (entries.length === 0) return '{}';
    const lines = entries
      .map(
        ([k, v]) =>
          `${indent}  ${JSON.stringify(k)}: ${serialise(v, indent + '  ')}`,
      )
      .join(',\n');
    return `{\n${lines},\n${indent}}`;
  }

  return String(value);
}

interface ProjectEntry {
  workspace: string;
  config: Record<string, unknown>;
}

function main(): void {
  const projects: ProjectEntry[] = [];

  for (const ws of workspaces) {
    const wsDir = path.join(repoRoot, ws);

    const hasCjs = fs.existsSync(path.join(wsDir, 'jest.config.cjs'));
    const hasTs = fs.existsSync(path.join(wsDir, 'jest.config.ts'));

    if (hasCjs && !hasTs) {
      throw new Error(
        `${ws} has jest.config.cjs but no jest.config.ts. ` +
          `Migrate it to jest.config.ts so the generator can handle it uniformly.`,
      );
    }

    if (!hasTs) {
      // No Jest config → no Jest tests (e.g. src/digital-letters-events)
      continue;
    }

    // Evaluate the workspace config in an isolated tsx subprocess so that the
    // shared mutable `baseJestConfig` object is freshly initialised for every
    // workspace. Dynamic import() in the parent process would share the cached
    // module instance and accumulate mutations.
    const configPath = path.join(wsDir, 'jest.config.ts');
    const tsxBin = path.join(repoRoot, 'node_modules', '.bin', 'tsx');
    const tmpFile = path.join(os.tmpdir(), `jest-config-eval-${Date.now()}.ts`);
    let json: string;
    try {
      fs.writeFileSync(tmpFile, EVALUATOR(configPath), 'utf8');
      json = execFileSync(tsxBin, [tmpFile], {
        cwd: repoRoot,
        encoding: 'utf8',
      });
    } finally {
      fs.rmSync(tmpFile, { force: true });
    }
    const wsConfig = JSON.parse(json) as Record<string, unknown>;

    // Inject rootDir and displayName. Jest resolves all relative paths inside a
    // project entry relative to that project's rootDir.
    const entry: Record<string, unknown> = {
      ...wsConfig,
      rootDir: `<rootDir>/${ws}`,
      displayName: ws,
    };

    projects.push({ workspace: ws, config: entry });
  }

  // Build the projects array source
  const projectLines = projects.map((p) => {
    const body = serialise(p.config, '    ');
    return `    // ${p.workspace}\n    ${body}`;
  });

  const banner = `/**
 * Root Jest config — runs all TypeScript workspace test suites in
 * parallel via Jest's native \`projects\` support.
 *
 * ⚠️  THIS FILE IS AUTO-GENERATED. Do not edit it directly.
 *
 * Generated by scripts/generate-parallel-jest-config.ts
 */

/** @type {import('jest').Config} */
module.exports = {
  projects: [
${projectLines.join(',\n\n')}
  ],
};
`;

  fs.writeFileSync(outputPath, banner, 'utf8');
  console.log(`Written: ${path.relative(repoRoot, outputPath)}`);
  console.log(`  ${projects.length} project(s) included`);
  for (const p of projects) {
    console.log(`    ${p.workspace}`);
  }
}

main();
