name: "Temp unit tests only"

on:
  workflow_dispatch:
    inputs:
      nodejs_version:
        description: "Node.js version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      python_version:
        description: "Python version, set by the CI/CD pipeline workflow"
        required: true
        type: string
  push:
    branches:
      - feature/CCM-14615_unit-test-quickening

env:
  AWS_REGION: eu-west-2
  TERM: xterm-256color

jobs:
  test-unit:
    name: "Unit tests"
    runs-on: ubuntu-latest
    timeout-minutes: 7
    permissions:
      contents: read
      packages: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - uses: ./.github/actions/node-install
        with:
          node-version: ${{ inputs.nodejs_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python_version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: "Run unit test suite"
        run: |
          make test-unit
      - name: "Save the result of fast test suite"
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests
          path: "**/.reports/unit"
          include-hidden-files: true
        if: always()
      - name: "Save the result of code coverage"
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ".reports/lcov.info"
      - name: "Save Python coverage reports"
        uses: actions/upload-artifact@v4
        with:
          name: python-coverage-reports
          path: |
            src/**/coverage.xml
            utils/**/coverage.xml
            lambdas/**/coverage.xml
